security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Utilisation de ton authentificateur personnalisé
            custom_authenticator: App\Security\UtilisateurAuthentificatorAuthenticator

            # Définir le entry_point pour savoir quel authentificateur utiliser
            entry_point: App\Security\UtilisateurAuthentificatorAuthenticator

            # Options pour le formulaire de connexion
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home

            logout:
                path: app_logout
                target: app_home

            # Si tu veux activer l'impersonation pour changer d'utilisateur
            # switch_user: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/pilote, roles: ROLE_PILOTE }
        - { path: ^/reservation, roles: ROLE_USER }
