controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    app_register:
        path: /register
        controller: App\Controller\SecurityController::register
        methods: [ GET, POST ]

    app_login:
        path: /login
        controller: App\Controller\SecurityController::login
        methods: [ GET, POST ]

    app_logout:
        path: /logout
        methods: [ GET ]
